services:
  db:
    image: postgres:16
    container_name: autoapply-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobs-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./init/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d jobs-db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  postgres_data:


