[project]
name = "autoapply"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.9.2",
    "numpy>=2.4.1",
    "playwright>=1.57.0",
    "pypdf>=6.6.0",
    "pyyaml>=6.0.3",
]
